// GENERATED by build.js — do not edit. Source: lib/abrp/*.js
(function () {
  var __mods = {};
  var __cache = {};
  function __require(id) {
    var nid = id.replace(/^\.\//, "").replace(/\.js$/, "");
    if (__cache[nid]) { return __cache[nid].exports; }
    // Unknown id: defer to the host require (not cached — host owns its caching).
    if (!__mods[nid]) {
      if (typeof require === "function") { return require(id); }
      throw new Error("Cannot find module: " + id);
    }
    var m = { exports: {} };
    __cache[nid] = m;
    __mods[nid](m, m.exports, __require);
    return m.exports;
  }
  __mods["abrp"] = function (module, exports, require) {
// https://docs.openvehicles.com/en/latest/userguide/scripting.html

// NOTE: const in duktape implementation is not much more than var offers
// https://wiki.duktape.org/postes5features

// Thin entry module: wires the focused lib/abrp/* modules together, exposes the
// in-vehicle entry points (info/onetime/send/resetConfig), and auto-starts inside
// OVMS. require()-able off-device (e.g. the node:test suite) with no side effects —
// the auto-start is guarded.
var C = require('./constants')
var U = require('./util')
var Cfg = require('./config')
var Met = require('./metrics')
var Q = require('./queue')
var Tlm = require('./telemetry')
var Ev = require('./events')
var Certs = require('./certs')
var Iternio = require('./iternio')
var Web = require('./web')
var Logger = U.Logger

// Core Control Functions

/**
 * Logs telemetry data to the console.
 */
function info() {
  var telemetry = Met.createTelemetry();

  // Helper function for formatting output
  function logTelemetry(key, label, unit) {
    unit = unit || '';  // Default to empty string if unit is not provided
    if (Object.prototype.hasOwnProperty.call(telemetry, key)) {
      Logger.log(label + ': ' + telemetry[key] + ' ' + unit);
    }
  }

  // Display plugin version
  Logger.log('Plugin Version: ' + C.VERSION);

  // Iterate over metricMap and display values if available
  Met.metricMap.forEach(function(item) {
    logTelemetry(item.key, item.label, item.unit);
  });
}

/**
 * Executes a one-time telemetry sending process.
 * Validates the user's ABRP configuration, creates telemetry data, and sends it.
 */
function onetime() {
  if (!Cfg.validate()) {
    return
  }
  Tlm.sendTelemetry(Met.createTelemetry())
}

/**
 * Resets the ABRP configuration to default values.
 */
function resetConfig() {
  Ev.send(0);
  Cfg.reset();
}

// Main Initialization Logic — only auto-start inside OVMS, so the module can be
// require()'d off-device (under the node:test suite) with no side effects.
if (typeof OvmsConfig !== 'undefined' &&
    typeof OvmsMetrics !== 'undefined' &&
    typeof PubSub !== 'undefined') {
  Ev.startup()
}

// Module exports
module.exports = {
  // Public, in-vehicle entry points (invoked via `script eval abrp.<fn>()`)
  info: info,
  onetime: onetime,
  send: Ev.send,
  resetConfig: resetConfig,
  webStatus: Web.webStatus,
  webIdentityRefresh: Web.webIdentityRefresh,
  // Pure helpers exercised by the test suite
  round: U.round,
  getOVMSMetric: Met.getOVMSMetric,
  createBulkPost: Tlm.createBulkPost,
  // Test-only seam (OVMS ignores extra exports; keeps the public surface clean)
  __test: {
    createTelemetry: Met.createTelemetry,
    sample: Q.sample,
    enqueue: Q.enqueue,
    roundTelemetry: Q.roundTelemetry,
    setSampleInterval: Q.setSampleInterval,
    getHeartbeatInterval: Q.getHeartbeatInterval,
    getChargePowerDeltaKw: Q.getChargePowerDeltaKw,
    adjustCadence: Q.adjustCadence,
    getEffectiveInterval: Q.getEffectiveInterval,
    getBaseline: Q.getBaseline,
    setSendInterval: Tlm.setSendInterval,
    callbackVehicleOn: Ev.callbackVehicleOn,
    callbackVehicleOff: Ev.callbackVehicleOff,
    manageVehicleStateEvents: Ev.manageVehicleStateEvents,
    applyIntervals: Ev.applyIntervals,
    sendBulkTelemetry: Tlm.sendBulkTelemetry,
    getQueue: Q.getQueue,
    setLastQueued: Q.setLastQueued,
    lastSend: Tlm.lastSend,
    isActive: Ev.isActive,
    meUrl: Iternio.meUrl,
    bootstrap: Certs.bootstrap,
    setCertDataLoader: Certs.__test.setCertDataLoader,
  },
}

  };
  __mods["certs"] = function (module, exports, require) {
// CA-certificate bootstrap: at first run, write the curated CA roots into
// /store/trustedca and run `tls trust reload`, gated by a config version stamp.
// Owns its own one-time state. Self-guards to a no-op when the host file/command
// APIs are absent (off-device, hand-install). Carries no PEM bytes — the cert
// data ships as a separate plugin element loaded via the host require.
var C = require('./constants')
var U = require('./util')
var Logger = U.Logger

// True only while an install is mid-flight, to guard against re-entry.
var inProgress = false

// Indirection so unit tests can inject fake cert data without resolving the
// external module. On-device this reaches the second plugin element through the
// host require (build.js defers unknown ids to it).
function defaultLoader() {
  return require('plugin/abrp/certdata')
}
var certDataLoader = defaultLoader

function setCertDataLoader(fn) {
  certDataLoader = fn
}

function bootstrap() {
  if (typeof VFS === 'undefined' ||
      typeof OvmsConfig === 'undefined' ||
      typeof OvmsCommand === 'undefined') {
    return // host APIs unavailable (off-device / hand-install)
  }
  if (inProgress) {
    return
  }

  var stamp = Number(OvmsConfig.Get('usr', 'abrp.certs_version', '0'));
  if (stamp >= C.CERTS_VERSION) {
    return // up to date — zero I/O
  }

  var certs;
  try {
    certs = certDataLoader();
  } catch (e) {
    Logger.error('Cert bootstrap: cert data unavailable (' + e + ')');
    return;
  }
  if (!certs || !certs.length) {
    Logger.error('Cert bootstrap: cert data empty');
    return;
  }

  inProgress = true;
  var total = certs.length;
  var settled = 0;
  var failed = false;

  function settle() {
    settled += 1;
    if (settled < total) {
      return;
    }
    inProgress = false;
    if (failed) {
      Logger.error('Cert bootstrap: a cert failed to write; will retry next start');
      return;
    }
    try {
      OvmsCommand.Exec('tls trust reload');
    } catch (e2) {
      Logger.error('Cert bootstrap: tls trust reload failed (' + e2 + ')');
      return;
    }
    OvmsConfig.Set('usr', 'abrp.certs_version', String(C.CERTS_VERSION));
    Logger.info('Cert bootstrap: installed ' + total + ' CA root(s)');
  }

  certs.forEach(function (cert) {
    VFS.Save({
      path: '/store/trustedca/' + cert.file,
      data: cert.pem,
      done: function () {
        settle();
      },
      fail: function (err) {
        failed = true;
        Logger.error('Cert bootstrap: failed to write ' + cert.file + ' (' + err + ')');
        settle();
      },
    });
  });
}

module.exports = {
  bootstrap: bootstrap,
  __test: {
    setCertDataLoader: setCertDataLoader,
  },
};

  };
  __mods["config"] = function (module, exports, require) {
// Owns the per-user ABRP token (usr abrp.user_token) read from OVMS config.
var C = require('./constants')
var user_token = (typeof OvmsConfig !== 'undefined')
  ? OvmsConfig.GetValues('usr', 'abrp.').user_token
  : undefined

/**
 * Returns the current user token (may be undefined if unset).
 */
function token() {
  return user_token
}

/**
 * Validates the ABRP configuration for the user.
 *
 * @returns {boolean} True if the configuration is valid, false otherwise.
 */
function validate() {
  // If user_token is not set or empty, attempt to populate it
  if (!user_token) {
    user_token = OvmsConfig.GetValues('usr', 'abrp.').user_token;
  }

  // If user_token is still not set, raise an error notification
  if (!user_token) {
    OvmsNotify.Raise(
      'error',
      'usr.abrp.status',
      'ABRP::config usr abrp.user_token not set'
    );
    return false;
  }
  return true;
}

/**
 * Deletes the stored user token and notifies that config was reset.
 */
function reset() {
  OvmsConfig.Delete('usr', 'abrp.user_token')
  OvmsNotify.Raise('info', 'usr.abrp.status', 'ABRP::usr abrp config reset')
}

/**
 * Returns the per-sample interval in seconds from usr abrp.sample_interval,
 * validated/clamped to 1..5, defaulting to SAMPLE_INTERVAL_DEFAULT.
 */
function sampleInterval() {
  var raw = (typeof OvmsConfig !== 'undefined')
    ? OvmsConfig.GetValues('usr', 'abrp.').sample_interval
    : undefined
  var n = parseInt(raw, 10)
  if (isNaN(n)) { return C.SAMPLE_INTERVAL_DEFAULT }
  if (n < 1) { return 1 }
  if (n > 5) { return 5 }
  return n
}

/**
 * Returns the bulk-flush interval in seconds from usr abrp.send_interval,
 * validated/clamped to 10..60, defaulting to SEND_INTERVAL_DEFAULT.
 */
function sendInterval() {
  var raw = (typeof OvmsConfig !== 'undefined')
    ? OvmsConfig.GetValues('usr', 'abrp.').send_interval
    : undefined
  var n = parseInt(raw, 10)
  if (isNaN(n)) { return C.SEND_INTERVAL_DEFAULT }
  if (n < 10) { return 10 }
  if (n > 60) { return 60 }
  return n
}

/**
 * Returns the stale-connection heartbeat interval in seconds from
 * usr abrp.heartbeat_interval. 0 disables the heartbeat; other values are
 * floored to 30 and capped at 3600; unset/invalid falls back to
 * HEARTBEAT_INTERVAL.
 */
function heartbeatInterval() {
  var raw = (typeof OvmsConfig !== 'undefined')
    ? OvmsConfig.GetValues('usr', 'abrp.').heartbeat_interval
    : undefined
  var n = parseInt(raw, 10)
  if (isNaN(n)) { return C.HEARTBEAT_INTERVAL }
  if (n <= 0) { return 0 }     // explicit disable
  if (n < 30) { return 30 }
  if (n > 3600) { return 3600 }
  return n
}

/**
 * Returns the charging-power deadband width in kW from
 * usr abrp.charge_power_delta_kw. 0 disables the deadband; negatives clamp to 0;
 * capped at 10; fractional allowed; unset/invalid falls back to
 * CHARGE_POWER_DELTA_KW.
 */
function chargePowerDeltaKw() {
  var raw = (typeof OvmsConfig !== 'undefined')
    ? OvmsConfig.GetValues('usr', 'abrp.').charge_power_delta_kw
    : undefined
  var n = parseFloat(raw)
  if (isNaN(n)) { return C.CHARGE_POWER_DELTA_KW }
  if (n < 0) { return 0 }
  if (n > 10) { return 10 }
  return n
}

module.exports = {
  token: token,
  validate: validate,
  reset: reset,
  sampleInterval: sampleInterval,
  sendInterval: sendInterval,
  heartbeatInterval: heartbeatInterval,
  chargePowerDeltaKw: chargePowerDeltaKw,
}

  };
  __mods["constants"] = function (module, exports, require) {
// Module + configuration constants (see CLAUDE.md "Tunable constants").
// Plain object so the bundler/Duktape treat it as a normal module export.
module.exports = {
  OVMS_API_KEY: '32b2162f-9599-4647-8139-66e9f9528370',
  VERSION: '3.0.0-alpha.5',
  CERTS_VERSION: 1, // bump when trustedca/ changes to force a one-time reinstall
  DEBUG: true,
  MAX_TELEMETRY_QUEUE_SIZE: 100,
  SAMPLE_INTERVAL_DEFAULT: 3, // seconds between samples; overridden by usr abrp.sample_interval (1-5)
  COLLECT_PRESSURE_FACTOR: 3, // collect > this x the rolling baseline counts as a slow collect (congestion)
  BACKOFF_MAX_INTERVAL: 180, // seconds; cap for the stretched sample interval under sustained congestion
  COLLECT_BASELINE_ALPHA: 0.25, // EWMA weight for updating the collect baseline on calm samples
  HEARTBEAT_INTERVAL: 160, // seconds; force a point if nothing queued for this long; 0 disables
  CHARGE_POWER_DELTA_KW: 1, // while charging, a power move smaller than this (vs the last queued point) is not a change — kills the DC-fast-charge sub-kW point flood
  SEND_INTERVAL_DEFAULT: 30, // seconds between bulk flushes; overridden by usr abrp.send_interval (10-60)
  ROUNDING: {
    soc: 0, power: 1, speed: 0, lat: 5, lon: 5, heading: 0, elevation: 0,
    ext_temp: 0, batt_temp: 0, cabin_temp: 0, hvac_setpoint: 0, hvac_power: 1,
    voltage: 0, current: 0, odometer: 1, est_battery_range: 0, soh: 0, soe: 1, capacity: 1,
    tire_pressure_fl: 0, tire_pressure_fr: 0, tire_pressure_rl: 0, tire_pressure_rr: 0,
  },
}

  };
  __mods["events"] = function (module, exports, require) {
// Event wiring + control flow: PubSub subscriptions, vehicle on/off callbacks,
// GPS-time gating, and the send() on/off switch. Owns subscriptions/isActive/
// time-valid state.
var U = require('./util')
var Cfg = require('./config')
var Met = require('./metrics')
var Q = require('./queue')
var Tlm = require('./telemetry')
var Certs = require('./certs')
var Logger = U.Logger

// Module state owned here.
var subscriptions = {};
var isActive = false;
var isSampling = false;
var _isTimeValid = false;

/**
 * Function to subscribe to events and store the token
 */
function subscribe(topic, callback) {
  var token = PubSub.subscribe(topic, callback);
  subscriptions[topic] = subscriptions[topic] || []; // Initialize array if not exists
  subscriptions[topic].push(token);
}

/**
 * Function to unsubscribe from events
 */
function unsubscribe(topic) {
  if (subscriptions[topic]) {
      for (var i = 0; i < subscriptions[topic].length; i++) {
          PubSub.unsubscribe(subscriptions[topic][i]);
      }
      delete subscriptions[topic]; // Optionally remove the topic from tracking
  }
}

/**
 * Handles the event when the vehicle is switched on.
 * Logs an informational message and sends an initial telemetry update to the queue.
 * Subscribes to the 'ticker.1' event to queue telemetry if necessary.
 *
 * @returns {void} - This function does not return a value; it performs actions related to the vehicle's power state.
 */
function callbackVehicleOn() {
  Logger.info('Vehicle switched on...');
  isSampling = true;
  Q.setSampleInterval(Cfg.sampleInterval());
  Q.setHeartbeatInterval(Cfg.heartbeatInterval());
  Q.setChargePowerDeltaKw(Cfg.chargePowerDeltaKw());
  Q.enqueue(Q.roundTelemetry(Met.createTelemetry()));   // full bookend, rounded
  subscribe('ticker.1', Q.sample);
}

/**
 * Handles vehicle off / charge stop. Unsubscribes the per-second sampler and
 * enqueues a final full bookend forced to a coherent parked state (speed/power 0,
 * is_parked true, is_charging/is_dcfc false).
 *
 * @returns {void} - This function does not return a value; it performs actions related to the vehicle's power state.
 */
function callbackVehicleOff() {
  Logger.info('Vehicle switched off...');
  isSampling = false;
  unsubscribe('ticker.1');
  var snap = Q.roundTelemetry(Met.createTelemetry());
  snap.speed = 0;
  snap.power = 0;
  snap.is_parked = true;
  snap.is_charging = false;
  snap.is_dcfc = false;
  Q.enqueue(snap);                                       // forced parked bookend
}

/**
 * Whether a telemetry session should be live, as a LEVEL: the vehicle is on
 * (driving) or charging. The four session events (vehicle.on/off,
 * charge.start/stop) are edges of these two independent states, so no single
 * edge can decide on its own — e.g. a charge.stop while the driver has already
 * powered up must NOT end the session.
 */
function isVehicleActive() {
  return Boolean(OvmsMetrics.Value('v.e.on')) || Boolean(OvmsMetrics.Value('v.c.charging'));
}

/**
 * Single handler for all four session events (and the cold-boot check): re-reads
 * the level and starts/stops the sampler only on an actual session transition.
 * isSampling makes overlapping edges idempotent — on + charging subscribes the
 * per-second sampler exactly once, and a charge.stop while still driving is a
 * no-op instead of killing the sampler mid-drive.
 */
function updateSamplingState() {
  var shouldSample = isVehicleActive();
  if (shouldSample && !isSampling) {
    callbackVehicleOn();
  } else if (!shouldSample && isSampling) {
    callbackVehicleOff();
  }
}

/**
 * Manages subscribing or unsubscribing to vehicle state events based on the provided parameter.
 *
 * If subscribing, it registers the level-based session handler for the four
 * vehicle state events and applies the current level (covering a (re)boot
 * mid-session, when the on/charge.start edges have already fired). If
 * unsubscribing, it removes all subscriptions it created and ends any live session.
 *
 * @param {boolean} shouldSubscribe - If true, subscribes to vehicle state events; if false, unsubscribes.
 *
 * @returns {void} - This function does not return a value; it modifies the subscription state for vehicle events.
 */
function manageVehicleStateEvents(shouldSubscribe) {
  if (shouldSubscribe) {
    Logger.debug('Subscribing to Vehicle State Events');
  } else {
    Logger.debug('Unsubscribing to Vehicle State Events');
  }

  if (shouldSubscribe) {
    subscribe('vehicle.type.set', Met.overrideMetricMap);
    subscribe('ticker.10', Tlm.sendBulkTelemetry)
    Tlm.setSendInterval(Cfg.sendInterval());
    subscribe('vehicle.on', updateSamplingState);
    subscribe('vehicle.charge.start', updateSamplingState);
    subscribe('vehicle.off', updateSamplingState);
    subscribe('vehicle.charge.stop', updateSamplingState);

    updateSamplingState();

  } else {
    unsubscribe('vehicle.on');
    unsubscribe('vehicle.charge.start');
    unsubscribe('vehicle.off');
    unsubscribe('vehicle.charge.stop');
    // Symmetric teardown: without these, every send(0)/send(1) cycle stacked an
    // extra ticker.10 / vehicle.type.set subscription.
    unsubscribe('vehicle.type.set');
    unsubscribe('ticker.10');
    if (isSampling) {
      callbackVehicleOff();
    }
  }

  isActive = shouldSubscribe;
}

/**
 * Monitors time and checks if it becomes valid, based on a minimum timestamp (Jan 1, 2000).
 * If valid, unsubscribes from the 'ticker.1' event and triggers startup logic.
 */
function checkTime() {
  const minValidTime = 946684800; // Unix timestamp for Jan 1, 2000
  if (OvmsMetrics.Value('m.time.utc') > minValidTime) {
    _isTimeValid = true;  // Mark the time as valid
    Logger.debug('GPS time is valid, unsubscribing from ticker.1');

    // Unsubscribe from the ticker.1 event once the time is valid
    unsubscribe('ticker.1');

    // Proceed with startup
    send(true);
  } else {
    Logger.debug('Invalid GPS time, skipping telemetry processing.');
  }
}

/**
 * Controls the sending of data based on the provided `shouldSend` flag.
 * @param {boolean} shouldSend - Indicates whether to start or stop sending data.
 */
function send(shouldSend) {
  // Check if config is valid
  if (!Cfg.validate()) return;

  // Check if time is valid
  if (!_isTimeValid) {
    Logger.error('Cannot send data: GPS time is invalid.');
    return;
  }

  if (shouldSend && !isActive) {
    Logger.info('Start sending data...');
    manageVehicleStateEvents(true);
  } else if (!shouldSend && isActive) {
    Logger.info('Stop sending data');
    manageVehicleStateEvents(false);
  } else {
    Logger.warn(isActive ? 'Already running!' : 'Already stopped!');
  }
}

/**
 * Whether GPS time has become valid (gates all sending).
 */
function isTimeValid() {
  return _isTimeValid
}

/**
 * Whether the plugin is actively wired to vehicle events / sending.
 */
function active() {
  return isActive
}

/**
 * Re-reads the tunable config keys and applies them, so a `config set` of
 * usr abrp.sample_interval / send_interval / heartbeat_interval /
 * charge_power_delta_kw takes effect on the next tick (no session restart).
 * Fired on OVMS `config.changed`, which carries no key, so all are re-read
 * unconditionally.
 */
function applyIntervals() {
  Q.setSampleInterval(Cfg.sampleInterval());
  Tlm.setSendInterval(Cfg.sendInterval());
  Q.setHeartbeatInterval(Cfg.heartbeatInterval());
  Q.setChargePowerDeltaKw(Cfg.chargePowerDeltaKw());
}

/**
 * Startup wiring: apply vehicle overrides and wait for valid GPS time.
 */
function startup() {
  Met.overrideMetricMap()
  Certs.bootstrap()
  subscribe('ticker.1', checkTime)
  subscribe('config.changed', applyIntervals)
}

module.exports = {
  subscribe: subscribe,
  unsubscribe: unsubscribe,
  send: send,
  checkTime: checkTime,
  manageVehicleStateEvents: manageVehicleStateEvents,
  callbackVehicleOn: callbackVehicleOn,
  callbackVehicleOff: callbackVehicleOff,
  isTimeValid: isTimeValid,
  isActive: active,
  startup: startup,
  applyIntervals: applyIntervals,
}

  };
  __mods["iternio"] = function (module, exports, require) {
// Light transport seam for the Iternio Telemetry API: URL builder + the
// HTTP-200-but-status-error check. The cert-heal hook (WS3) will live here too.
var C = require('./constants')
var U = require('./util')
var Logger = U.Logger

/**
 * Builds an Iternio API URL for the given path (e.g. 'tlm/send', 'tlm/bulk'),
 * with the plugin's app api_key already appended.
 */
function apiUrl(path) {
  return 'https://api.iternio.com/1/' + path + '?api_key=' + encodeURIComponent(C.OVMS_API_KEY)
}

/**
 * Builds the Iternio oauth/me URL for the given access token (api_key + token).
 */
function meUrl(token) {
  return apiUrl('oauth/me') + '&access_token=' + encodeURIComponent(token)
}

/**
 * The Iternio API returns HTTP 200 even for application-level errors, signalling
 * the real outcome via a JSON body {"status":"ok"|"error"}. Returns true only
 * when the body parses and status === 'ok'. Defensive: a missing/malformed body
 * is treated as NOT ok.
 */
function isApiOk(body) {
  if (!body) {
    return false
  }
  try {
    return JSON.parse(body).status === 'ok'
  } catch (e) {
    Logger.warn('Could not parse ABRP response body', body)
    return false
  }
}

module.exports = {
  apiUrl: apiUrl,
  meUrl: meUrl,
  isApiOk: isApiOk,
}

  };
  __mods["metrics"] = function (module, exports, require) {
// Owns metricMap (the ABRP<->OVMS metric mapping) and the functions that read
// OVMS metrics through it. See CLAUDE.md "Architecture" for why metricMap is the
// heart of the design.
var U = require('./util')
var Logger = U.Logger

/**
 * metricMap defines a list of ABRP (A Better Routeplanner) metrics and their
 *   corresponding OVMS (Open Vehicle Monitoring System) metrics.
 *
 * Each entry in metricMap contains the following properties:
 * - key: A unique identifier for the metric from the Iternio Telemetry API.
 * - label: A descriptive name for the metric to be displayed in UI or logs.
 * - unit: (Optional) The unit of measurement for the metric.
 * - requiredMetrics: An array of OVMS metrics that are required to calculate the value of the metric.
 *     If requiredMetrics is empty, the metric is not supported or cannot be calculated from the available data.
 * - metric: A function that processes the telemetry data and returns the value for the metric.
 *
 * Vehicle-Specific Implementations:
 * A function called `overrideMetricMap` can be used to modify the default `metricMap` on startup,
 *   allowing vehicle-specific implementations or adjustments to certain metrics.
 */
var metricMap = [
  { key: 'utc', label: 'UTC Timestamp', unit: 's' , requiredMetrics: ['m.time.utc'] ,
      metric: function(metrics) { return metrics['m.time.utc']; } },
  { key: 'soc', label: 'State of Charge', unit: '%' , requiredMetrics: ['v.b.soc'] ,
      metric: function(metrics) { return metrics['v.b.soc']; } },
  { key: 'power', label: 'Battery Power', unit: 'kW' , requiredMetrics: ['v.b.power'] ,
      metric: function(metrics) { return metrics['v.b.power']; } },
  { key: 'speed', label: 'Vehicle Speed', unit: 'kph' , requiredMetrics: ['v.p.speed'] ,
      metric: function(metrics) { return metrics['v.p.speed']; } },
  { key: 'lat', label: 'GPS Latitude', unit: '°' , requiredMetrics: ['v.p.latitude'] ,
      metric: function(metrics) { return metrics['v.p.latitude']; } },
  { key: 'lon', label: 'GPS Longitude', unit: '°' , requiredMetrics: ['v.p.longitude'] ,
      metric: function(metrics) { return metrics['v.p.longitude']; } },
  { key: 'is_charging', label: 'Charging' , requiredMetrics: ['v.c.charging'] ,
      metric: function(metrics) { return metrics['v.c.charging']; } },
  { key: 'is_dcfc', label: 'DC Fast Charging' , requiredMetrics: ['v.c.mode'] ,
      metric: function(metrics) { return metrics['v.c.mode'] === 'performance'; } },
  { key: 'is_parked', label: 'Parked' , requiredMetrics: ['v.e.parktime'] ,
      metric: function(metrics) { return metrics['v.e.parktime'] > 0; } },
  { key: 'capacity', label: 'Capacity', unit: 'kWh' , requiredMetrics: ['v.b.capacity'] ,
      metric: function(metrics) { return metrics['v.b.capacity']; } },
  { key: 'soe', label: 'Present Energy', unit: 'kWh' , requiredMetrics: ['v.b.soc', 'v.b.capacity'] ,
      metric: function(metrics) { return (metrics['v.b.soc'] / 100) * metrics['v.b.capacity']; } },
  { key: 'soh', label: 'State of Health', unit: '%' , requiredMetrics: ['v.b.soh'] ,
      metric: function(metrics) { return metrics['v.b.soh']; } },
  { key: 'heading', label: 'GPS Heading', unit: '°' , requiredMetrics: ['v.p.direction'] ,
      metric: function(metrics) { return metrics['v.p.direction']; } },
  { key: 'elevation', label: 'GPS Elevation', unit: 'm' , requiredMetrics: ['v.p.altitude'] ,
      metric: function(metrics) { return metrics['v.p.altitude']; } },
  { key: 'ext_temp', label: 'External Temp', unit: '°C' , requiredMetrics: ['v.e.temp'] ,
      metric: function(metrics) { return metrics['v.e.temp']; } },
  { key: 'batt_temp', label: 'Battery Temp', unit: '°C' , requiredMetrics: ['v.b.temp'] ,
      metric: function(metrics) { return metrics['v.b.temp']; } },
  { key: 'voltage', label: 'Battery Voltage', unit: 'V' , requiredMetrics: ['v.b.voltage'] ,
      metric: function(metrics) { return metrics['v.b.voltage']; } },
  { key: 'current', label: 'Battery Current', unit: 'A' , requiredMetrics: ['v.b.current'] ,
      metric: function(metrics) { return metrics['v.b.current']; } },
  { key: 'odometer', label: 'Odometer', unit: 'km' , requiredMetrics: ['v.p.odometer'] ,
      metric: function(metrics) { return metrics['v.p.odometer']; } },
  { key: 'est_battery_range', label: 'Estimated Range', unit: 'km' , requiredMetrics: ['v.b.range.est'] ,
      metric: function(metrics) { return metrics['v.b.range.est']; } },
  // No generic OVMS source for HVAC power; supply via overrideMetricMap() on
  // vehicles that expose it (e.g. an x… extended metric). Unmapped => auto-skipped.
  { key: 'hvac_power', label: 'HVAC Power', unit: 'kW' , requiredMetrics: []  },
  { key: 'hvac_setpoint', label: 'HVAC Setpoint', unit: '°C' , requiredMetrics: ['v.e.cabinsetpoint'] ,
      metric: function(metrics) { return metrics['v.e.cabinsetpoint']; } },
  { key: 'cabin_temp', label: 'Cabin Temp', unit: '°C' , requiredMetrics: ['v.e.cabintemp'] ,
      metric: function(metrics) { return metrics['v.e.cabintemp']; } },
  // OVMS exposes tyre data as a vector metric; wheel order is fixed: FL=0, FR=1, RL=2, RR=3.
  { key: 'tire_pressure_fl', label: 'FL Tire Pressure', unit: 'kPa' , requiredMetrics: ['v.t.pressure'] ,
      metric: function(metrics) { return metrics['v.t.pressure'][0]; } },
  { key: 'tire_pressure_fr', label: 'FR Tire Pressure', unit: 'kPa' , requiredMetrics: ['v.t.pressure'] ,
      metric: function(metrics) { return metrics['v.t.pressure'][1]; } },
  { key: 'tire_pressure_rl', label: 'RL Tire Pressure', unit: 'kPa' , requiredMetrics: ['v.t.pressure'] ,
      metric: function(metrics) { return metrics['v.t.pressure'][2]; } },
  { key: 'tire_pressure_rr', label: 'RR Tire Pressure', unit: 'kPa' , requiredMetrics: ['v.t.pressure'] ,
      metric: function(metrics) { return metrics['v.t.pressure'][3]; } },
];

/**
 * Updates the `metricMap` based on the vehicle type retrieved from the OvmsMetrics service.
 * Additional cases for other vehicle types can be added as needed.
 */
function overrideMetricMap() {
  Logger.debug("Running overrideMetricMap...");

  var vehicleType = OvmsMetrics.Value('v.type');
  Logger.debug("Vehicle type: " + vehicleType);

  metricMap.forEach(function(entry) {
    switch (vehicleType) {
      case 'KS':
        // Kia Soul has an OVMS bug for calculating SOH. This removes it from being reported.
        if (entry.key === 'soh') {
          delete entry.requiredMetrics;
          delete entry.metric;
        }
        break;
      case 'NL':
        if (entry.key === 'soc') {
          entry.requiredMetrics = ['xnl.v.b.soc.instrument'];
          entry.metric = function(metrics) {
            return metrics['xnl.v.b.soc.instrument'];
          };
        }
        if (entry.key === 'soh') {
            entry.requiredMetrics = ['xnl.v.b.soh.instrument'];
            entry.metric = function(metrics) {
              return metrics['xnl.v.b.soh.instrument'];
            };
          }
        if (entry.key === 'est_battery_range') {
          entry.requiredMetrics = ['xnl.v.b.range.instrument', 'v.b.range.ideal'];
          entry.metric = function(metrics) {
            var instrumentRange = metrics['xnl.v.b.range.instrument'] || 0;
            var idealRange = metrics['v.b.range.ideal'];
            return idealRange > 1.1 * instrumentRange ? idealRange : instrumentRange;
          };
        }
        break;
      case 'SUBSOL':
      case 'TOYBZ4X':
        if (entry.key === 'is_parked') {
          entry.requiredMetrics = ['v.e.gear'];
          entry.metric = function(metrics) {
            return metrics['v.e.gear'] === 0;
          };
        }
        if (entry.key === 'hvac_power') {
          entry.requiredMetrics = ['xte.v.e.hvac.power'];
          entry.metric = function(metrics) {
            return metrics['xte.v.e.hvac.power'];
          };
        }
        break;
      // Add cases for other vehicle types as needed
    }
  });
}

/**
 * Checks if all the required metrics are supported by the OvmsMetrics system.
 * @param {Array} requiredMetrics - An array of required metric names to be checked.
 * @returns {boolean} - Returns true if all the required metrics are supported, false otherwise.
 */
function isOvmsMetricSupported(requiredMetrics) {
  for (var i = 0; i < requiredMetrics.length; i++) {
    if (!OvmsMetrics.HasValue(requiredMetrics[i])) {
      return false; // Return false if any metric is not defined or stale
    }
  }
  return true; // All metrics are supported
}

/**
 * Retrieves the value of the specified OVMS metric parameter.
 * @param {string} parameter - The parameter name of the OVMS metric.
 * @returns {[boolean, any]} - Returns a two-element array. The first element indicates whether the metric is supported, and the second element is the metric value. If the parameter is unrecognized, the array will contain [false, null].
 */
function getOVMSMetric(parameter) {
  // Search through metricMap to find the matching entry
  var telemetryEntry = null;
  for (var i = 0; i < metricMap.length; i++) {
    if (metricMap[i].key === parameter) {
      telemetryEntry = metricMap[i];
      break;
    }
  }

  if (telemetryEntry) {
    // If requiredMetrics is an empty array, return unsupported
    if (!telemetryEntry.requiredMetrics || telemetryEntry.requiredMetrics.length === 0) {
      return [false, null];
    }

    // Check if all required metrics are supported
    var isSupported = isOvmsMetricSupported(telemetryEntry.requiredMetrics);

    if (isSupported) {
      // Retrieve the metrics values
      var metrics = OvmsMetrics.GetValues(telemetryEntry.requiredMetrics);
      var value = telemetryEntry.metric(metrics); // Pass metrics
      return [true, value];
    } else {
      return [false, null];
    }
  } else {
    // If the parameter is not found in metricMap, return [false, null]
    return [false, null];
  }
}

/**
 * Creates a telemetry object with the specified parameters.
 *
 * @returns {Object} The telemetry object containing the supported parameters and their values.
 */
function createTelemetry() {
  var telemetry = {};  // Creating an empty object to hold the telemetry data

  // Use metricMap to fetch and store telemetry data
  metricMap.forEach(function(entry) {
    var key = entry.key;

    var result = getOVMSMetric(key);  // Fetch the metric for the current key
    var isSupported = result[0];
    var value = result[1];

    if (isSupported) {
      telemetry[key] = value;  // Add the value to the telemetry object
    }
  });

  return telemetry;  // Returning the telemetry object
}

module.exports = {
  metricMap: metricMap,
  overrideMetricMap: overrideMetricMap,
  getOVMSMetric: getOVMSMetric,
  createTelemetry: createTelemetry,
}

  };
  __mods["queue"] = function (module, exports, require) {
// Owns the telemetry queue, the change-based sampling gate, and the overflow drop. Other
// modules read/mutate this state only through the accessors exported below.
var C = require('./constants')
var U = require('./util')
var Met = require('./metrics')
var Logger = U.Logger
var round = U.round

// Module state owned by this module.
var telemetryToSend = []
var lastQueuedTelemetry = {
  utc: 0,
}
var lastSampleMono = 0
var lastQueuedMono = 0
var baseInterval = C.SAMPLE_INTERVAL_DEFAULT   // configured floor (usr abrp.sample_interval)
var effectiveInterval = baseInterval           // what the gate uses; never below baseInterval
var collectBaseline = null                     // EWMA of calm collect durations (ms); null until seeded
var heartbeatInterval = C.HEARTBEAT_INTERVAL   // usr abrp.heartbeat_interval; 0 disables
var chargeDeltaKw = C.CHARGE_POWER_DELTA_KW    // usr abrp.charge_power_delta_kw

var ROUNDING = C.ROUNDING

/**
 * Rounds each telemetry field that has a precision in ROUNDING (in place).
 * Unmapped keys (utc, booleans) are left untouched. Returns the same object.
 */
function roundTelemetry(snap) {
  for (var k in snap) {
    if (Object.prototype.hasOwnProperty.call(ROUNDING, k)) {
      snap[k] = round(snap[k], ROUNDING[k])
    }
  }
  return snap
}

/**
 * Charging-power jitter under CHARGE_POWER_DELTA_KW should not force a queued
 * point (the DC-fast-charge flood fix, ported from 2.3.0). Measured against the
 * last queued power so a slow ramp still accumulates to a queued point; SoC and
 * state changes are carried by the other fields and still queue normally. Only
 * applies while charging — the driving path is unaffected.
 */
function withinChargeDeadband(snap) {
  return snap.is_charging &&
    typeof lastQueuedTelemetry.power === 'number' &&
    Math.abs(snap.power - lastQueuedTelemetry.power) < chargeDeltaKw
}

/**
 * True if any non-utc field of snap differs from the last queued point (with the
 * charging-power deadband applied to the power field).
 */
function changedVsLastQueued(snap) {
  for (var k in snap) {
    if (k === 'utc') { continue }
    if (k === 'power' && withinChargeDeadband(snap)) { continue }
    if (snap[k] !== lastQueuedTelemetry[k]) { return true }
  }
  return false
}

/**
 * Sets the per-session sample interval (seconds) and resets the adaptive cadence
 * to that floor. Called at session start and on config.changed. The collect
 * baseline persists (it is a device/vehicle characteristic, not session state).
 */
function setSampleInterval(n) {
  baseInterval = n
  effectiveInterval = n
}

/**
 * Sets the stale-connection heartbeat interval (seconds); 0 disables it.
 * Applied at session start and on config.changed (usr abrp.heartbeat_interval).
 */
function setHeartbeatInterval(n) {
  heartbeatInterval = n
}

/**
 * Sets the charging-power deadband width (kW); 0 disables the deadband.
 * Applied at session start and on config.changed (usr abrp.charge_power_delta_kw).
 */
function setChargePowerDeltaKw(n) {
  chargeDeltaKw = n
}

/**
 * Unconditionally queues a full snapshot, stamps the cadence baselines from
 * m.monotonic, and applies the overflow drop (oldest first).
 */
function enqueue(snap) {
  var mono = OvmsMetrics.Value('m.monotonic')
  telemetryToSend.push(snap)
  lastQueuedTelemetry = snap
  lastQueuedMono = mono
  lastSampleMono = mono
  if (telemetryToSend.length > C.MAX_TELEMETRY_QUEUE_SIZE) {
    telemetryToSend.shift()
    Logger.warn('Telemetry queue exceeded ' + C.MAX_TELEMETRY_QUEUE_SIZE + ' items. Oldest entry dropped.')
  }
  Logger.debug('Telemetry queued, data in queue:', telemetryToSend.length)
}

/**
 * Congestion controller. Given the latest collect duration (ms), stretches or
 * relaxes effectiveInterval. A collect slower than COLLECT_PRESSURE_FACTOR x the
 * rolling baseline is treated as event-loop congestion: multiplicative increase,
 * capped at BACKOFF_MAX_INTERVAL. A calm collect updates the EWMA baseline and
 * multiplicatively recovers toward baseInterval. Slow collects never update the
 * baseline (so a spike cannot desensitize the threshold).
 * Takes no hidden time reads, so it is fully determined by ms + current module state (testable with a plain number).
 */
function adjustCadence(ms) {
  if (ms <= 0) { return }   // ignore zero/negative timings (coarse clock); never seed/poison baseline on them
  if (collectBaseline === null) {
    collectBaseline = ms
    return
  }
  if (ms > collectBaseline * C.COLLECT_PRESSURE_FACTOR) {
    effectiveInterval = Math.min(effectiveInterval * 2, C.BACKOFF_MAX_INTERVAL)
  } else {
    collectBaseline = collectBaseline + C.COLLECT_BASELINE_ALPHA * (ms - collectBaseline)
    if (effectiveInterval > baseInterval) {
      effectiveInterval = Math.max(Math.floor(effectiveInterval / 2), baseInterval)
    }
  }
  if (C.DEBUG) {
    Logger.debug('cadence: collect_ms=' + ms.toFixed(1) + ' baseline=' + collectBaseline.toFixed(1) + ' interval=' + effectiveInterval)
  }
}

/**
 * Per-tick sampler (subscribed to ticker.1). Gated on m.monotonic elapsed time;
 * queues a rounded full snapshot only when a field changed, or on the heartbeat.
 */
function sample() {
  var mono = OvmsMetrics.Value('m.monotonic')
  if (mono - lastSampleMono < effectiveInterval) { return }
  lastSampleMono = mono
  var t0 = performance.now()
  var snap = roundTelemetry(Met.createTelemetry())
  adjustCadence(performance.now() - t0)
  if (changedVsLastQueued(snap)) {
    enqueue(snap)
  } else if (heartbeatInterval > 0 && mono - lastQueuedMono >= heartbeatInterval) {
    enqueue(snap)
  }
}

/**
 * Removes the given batch's telemetry objects from the queue by identity. A
 * successful flush thus drops only the points that were actually sent, even if
 * the queue's front shifted (an overflow drop) while the request was in flight —
 * unlike a positional splice, which could discard never-sent points. Objects
 * already removed (e.g. shifted out as overflow) are simply not found.
 */
function removeTelemetryBatch(batch) {
  for (var i = 0; i < batch.length; i++) {
    var idx = telemetryToSend.indexOf(batch[i]);
    if (idx !== -1) {
      telemetryToSend.splice(idx, 1);
    }
  }
}

/**
 * Returns a shallow snapshot of up to `n` queued points from the front.
 */
function snapshot(n) {
  return telemetryToSend.slice(0, n)
}

module.exports = {
  roundTelemetry: roundTelemetry,
  changedVsLastQueued: changedVsLastQueued,
  setSampleInterval: setSampleInterval,
  setHeartbeatInterval: setHeartbeatInterval,
  setChargePowerDeltaKw: setChargePowerDeltaKw,
  getHeartbeatInterval: function () { return heartbeatInterval },
  getChargePowerDeltaKw: function () { return chargeDeltaKw },
  enqueue: enqueue,
  sample: sample,
  removeTelemetryBatch: removeTelemetryBatch,
  snapshot: snapshot,
  adjustCadence: adjustCadence,
  getEffectiveInterval: function () { return effectiveInterval },
  getBaseline: function () { return collectBaseline },
  getQueue: function () { return telemetryToSend },
  setLastQueued: function (o) { lastQueuedTelemetry = o },
  setLastSampleMono: function (n) { lastSampleMono = n },
}

  };
  __mods["telemetry"] = function (module, exports, require) {
// Transmission: single-shot send (onetime) + bulk flush of the queue. Owns the
// in-flight guard (isSending) so overlapping bulk requests can't race.
var C = require('./constants')
var U = require('./util')
var Cfg = require('./config')
var Q = require('./queue')
var Iternio = require('./iternio')
var Logger = U.Logger
var clone = U.clone

// Module state: in-flight guard + flush cadence (m.monotonic-gated).
var isSending = false
var lastFlushMono = 0
var sendInterval = C.SEND_INTERVAL_DEFAULT
var lastResult = null

/**
 * Logs the telemetry list (tlm_list) from a bulk telemetry post object.
 */
function logTlmList(bulkPost) {
  if (bulkPost && bulkPost.data && bulkPost.data.length > 0) {
    var tlmList = bulkPost.data[0].tlm_list; // Access the tlm_list

    tlmList.forEach(function(item) {
      Logger.debug('Sending: ' + JSON.stringify(item));
    });
  }
}

/**
 * Sends single telemetry data to the ABRP (A Better Routeplanner) API.
 * Only used in oneTime()
 * @param {Object} telemetry - The telemetry data to be sent to ABRP.
 */
function sendTelemetry(telemetry) {
  Logger.info('Sending telemetry to ABRP', telemetry)
  var url =
    Iternio.apiUrl('tlm/send') +
    '&token=' +
    encodeURIComponent(Cfg.token()) +
    '&tlm=' +
    encodeURIComponent(JSON.stringify(telemetry))

  // Perform the HTTP request
  HTTP.Request({
    url: url,
    timeout: 5000,
    done: function (response) {
      if (response.statusCode === 200 && Iternio.isApiOk(response.body)) {
        Logger.debug('Telemetry data sent successfully.')
      } else {
        Logger.warn('ABRP did not accept telemetry', response)
      }
    },
    fail: function (error) {
      Logger.error('ABRP error', error);
    },
  });
}

/**
 * Delta-encodes a batch of full snapshots for transmission: the first point is
 * full (a resync), each subsequent point carries utc + only the fields that
 * changed from the previous point. Does not mutate the input points.
 */
function deltaEncode(batch) {
  var out = []
  var prev = null
  for (var i = 0; i < batch.length; i++) {
    var p = batch[i]
    if (prev === null) {
      out.push(clone(p))
    } else {
      var d = { utc: p.utc }
      for (var k in p) {
        if (k !== 'utc' && p[k] !== prev[k]) { d[k] = p[k] }
      }
      out.push(d)
    }
    prev = p
  }
  return out
}

/**
 * Builds a bulk telemetry post object for the given batch (the queued points to
 * send — delta-encoded for transmission).
 */
function createBulkPost(batch) {
  return {
    data: [
      {
        token: Cfg.token(),
        tlm_list: deltaEncode(batch),
      },
    ],
  }
}

/**
 * Sets the bulk-flush interval in seconds. Called at session start; a raw 0
 * disables the gate (flush on every tick) — used by tests.
 */
function setSendInterval(n) {
  sendInterval = n
}

/**
 * Flushes queued telemetry to the ABRP bulk endpoint. Sends at most one batch
 * per call, never overlaps in-flight requests, and only removes points from the
 * queue once the API confirms success (HTTP 200 AND body status === 'ok').
 */
function sendBulkTelemetry() {
  if (isSending) {
    Logger.debug('Bulk send already in progress; skipping this tick.')
    return
  }
  var mono = OvmsMetrics.Value('m.monotonic')
  if (mono - lastFlushMono < sendInterval) {
    return // not time to flush yet
  }
  if (Q.getQueue().length === 0) {
    return // nothing to send; leave lastFlushMono unstamped so that once a flush has occurred, later data flushes promptly (the first flush after boot is gated like any other)
  }
  lastFlushMono = mono

  // Snapshot the batch now so the removal count cannot drift if more telemetry
  // is queued while the request is in flight.
  var batch = Q.snapshot(C.MAX_TELEMETRY_QUEUE_SIZE) // the whole queue (capped by MAX_TELEMETRY_QUEUE_SIZE)
  var bulkPost = createBulkPost(batch)
  var url = Iternio.apiUrl('tlm/bulk')

  Logger.debug('Sending bulk telemetry to ABRP')
  isSending = true
  try {
    HTTP.Request({
      url: url,
      headers: [{ 'Content-Type': 'application/json' }],
      post: JSON.stringify(bulkPost),
      timeout: 8000, // must complete within ticker.10
      done: function (response) {
        isSending = false
        if (response.statusCode === 200 && Iternio.isApiOk(response.body)) {
          Logger.debug('Bulk telemetry accepted. Removing batch from queue.')
          logTlmList(bulkPost)
          // Remove exactly the sent objects by identity, so an overflow drop that
          // shifted the queue front mid-flight can't discard never-sent points.
          Q.removeTelemetryBatch(batch)
          lastResult = { ok: true, code: response.statusCode, count: batch.length, ts: U.timestamp() }
        } else {
          Logger.warn('ABRP rejected bulk telemetry; keeping batch for retry', response)
          lastResult = { ok: false, code: response.statusCode, count: batch.length, ts: U.timestamp() }
        }
      },
      fail: function (error) {
        isSending = false
        lastResult = { ok: false, error: String(error), count: batch.length, ts: U.timestamp() }
        Logger.error('ABRP error', error)
      },
    })
  } catch (e) {
    isSending = false
    Logger.error('HTTP.Request threw synchronously', e)
  }
}

/**
 * Returns the last bulk-flush result ({ok, code|error, count, ts}) or null if no
 * flush has completed yet. Read-only; used by the web status surface.
 */
function lastSend() {
  return lastResult
}

module.exports = {
  sendTelemetry: sendTelemetry,
  sendBulkTelemetry: sendBulkTelemetry,
  createBulkPost: createBulkPost,
  setSendInterval: setSendInterval,
  lastSend: lastSend,
}

  };
  __mods["util"] = function (module, exports, require) {
// Utility functions (pure helpers + the Logger). No module state.
var C = require('./constants')

/**
 * Creates a shallow copy of the provided object.
 */
function clone(obj) {
  return Object.assign({}, obj)
}

/**
 * Rounds the given number to the specified precision.
 */
function round(number, precision) {
  if (!number) {
    return number // could be 0, null or undefined
  }
  return Number(number.toFixed(precision || 0))
}

/**
 * Returns the current date and time as a localized string.
 */
function timestamp() {
  return new Date().toLocaleString()
}

/**
 * Creates a logger object with various logging functions.
 *
 * @returns {Object} - An object with logging functions (log, debug, error, info, warn).
 */
function logger() {
  function log(message, obj) {
    print(message + (obj ? ' ' + JSON.stringify(obj) : '') + '\n')
  }

  function debug(message, obj) {
    if (C.DEBUG) {
      log('(' + timestamp() + ') DEBUG: ' + message, obj)
    }
  }

  function error(message, obj) {
    log('(' + timestamp() + ') ERROR: ' + message, obj)
  }

  function info(message, obj) {
    log('(' + timestamp() + ') INFO: ' + message, obj)
  }

  function warn(message, obj) {
    log('(' + timestamp() + ') WARN: ' + message, obj)
  }

  return {
    debug,
    error,
    info,
    log,
    warn,
  }
}

var Logger = logger()

module.exports = {
  Logger: Logger,
  round: round,
  clone: clone,
  timestamp: timestamp,
}

  };
  __mods["web"] = function (module, exports, require) {
// Web read-surface: functions the plugin web pages call via the OVMS command
// bridge (loadcmd "script eval abrp.webStatus()"). webStatus() prints a JSON
// status snapshot (synchronous, no network). webIdentityRefresh() fires an async
// oauth/me call and caches the identity. Owns only the identity cache.
var C = require('./constants')
var Cfg = require('./config')
var Met = require('./metrics')
var Q = require('./queue')
var Tlm = require('./telemetry')
var Ev = require('./events')
var Iternio = require('./iternio')

// Expose getOVMSMetric via the metrics module accessor (avoids the timing
// Logger.debug call in createTelemetry, keeping webStatus output pure JSON).
var getOVMSMetric = Met.getOVMSMetric

// Cached result of the last oauth/me call. state: unknown|checking|ok|error.
var identity = { state: 'unknown' }

// Telemetry fields surfaced on the dashboard (a curated subset of the full map).
var KEY_TELEMETRY = ['soc', 'power', 'speed', 'is_charging']

/**
 * Prints a one-line JSON status snapshot for the web pages. Synchronous, no
 * network, defensive: any internal error is printed as {"error":...} rather than
 * thrown into the command layer.
 */
function webStatus() {
  try {
    var tele = {}
    for (var i = 0; i < KEY_TELEMETRY.length; i++) {
      var k = KEY_TELEMETRY[i]
      var result = getOVMSMetric(k)
      if (result[0]) {
        tele[k] = result[1] !== undefined ? result[1] : null
      }
    }
    var snap = {
      version: C.VERSION,
      token_set: !!Cfg.token(),
      time_valid: Ev.isTimeValid(),
      sending: Ev.isActive(),
      queue_depth: Q.getQueue().length,
      last_send: Tlm.lastSend(),
      identity: identity,
      telemetry: tele,
    }
    print(JSON.stringify(snap))
  } catch (e) {
    print(JSON.stringify({ error: String(e) }))
  }
}

/**
 * Fires an async oauth/me call to validate the configured token and cache the
 * identity. Prints a synchronous ack; the done/fail callbacks only mutate the
 * cache (webStatus surfaces it). No-ops to an error state if HTTP is unavailable
 * or no token is set.
 */
function webIdentityRefresh() {
  if (typeof HTTP === 'undefined' || !Cfg.token()) {
    identity = { state: 'error', error: 'no token' }
    print('{"ok":false}')
    return
  }
  identity = { state: 'checking' }
  HTTP.Request({
    url: Iternio.meUrl(Cfg.token()),
    timeout: 5000,
    done: function (response) {
      if (response.statusCode === 200 && Iternio.isApiOk(response.body)) {
        // Safe: isApiOk() above already parsed/validated this body.
        var b = JSON.parse(response.body)
        identity = {
          state: 'ok',
          name: b.full_name,
          vehicle: b.vehicle_name,
          typecode: b.vehicle_typecode,
        }
      } else {
        identity = { state: 'error', error: 'rejected' }
      }
    },
    fail: function (error) {
      identity = { state: 'error', error: String(error) }
    },
  })
  print('{"ok":true}')
}

module.exports = {
  webStatus: webStatus,
  webIdentityRefresh: webIdentityRefresh,
  __test: {
    getIdentity: function () {
      return identity
    },
  },
}

  };
  module.exports = __require("abrp");
})();
