// Dependency-free CommonJS bundler for the OVMS/Duktape deliverable.
// Concatenates lib/abrp/*.js modules (relative requires resolved here) into one
// self-contained, Duktape-safe file. Usage:
//   node build.js --src lib/abrp --entry abrp --out dist/abrp.js
var fs = require('fs')
var path = require('path')

function arg(name, def) {
  var i = process.argv.indexOf('--' + name)
  return i !== -1 ? process.argv[i + 1] : def
}

var srcDir = path.resolve(arg('src', 'lib/abrp'))
var entry = arg('entry', 'abrp')
var outFile = path.resolve(arg('out', 'dist/abrp.js'))

// Normalize a require id to a bare module name (all modules live in one dir).
function norm(id) {
  return id.replace(/^\.\//, '').replace(/\.js$/, '')
}

// Collect every .js module in the source dir (excluding *.test.js).
var modules = {}
fs.readdirSync(srcDir).forEach(function (f) {
  if (/\.js$/.test(f) && !/\.test\.js$/.test(f)) {
    modules[norm(f)] = fs.readFileSync(path.join(srcDir, f), 'utf8')
  }
})

// Emit: a tiny CommonJS registry + each module as a factory + the entry export.
var out = []
out.push('// GENERATED by build.js — do not edit. Source: lib/abrp/*.js')
out.push('(function () {')
out.push('  var __mods = {};')
out.push('  var __cache = {};')
out.push('  function __require(id) {')
out.push('    var nid = id.replace(/^\\.\\//, "").replace(/\\.js$/, "");')
out.push('    if (__cache[nid]) { return __cache[nid].exports; }')
out.push('    // Unknown id: defer to the host require (not cached — host owns its caching).')
out.push('    if (!__mods[nid]) {')
out.push('      if (typeof require === "function") { return require(id); }')
out.push('      throw new Error("Cannot find module: " + id);')
out.push('    }')
out.push('    var m = { exports: {} };')
out.push('    __cache[nid] = m;')
out.push('    __mods[nid](m, m.exports, __require);')
out.push('    return m.exports;')
out.push('  }')
Object.keys(modules).forEach(function (name) {
  out.push('  __mods[' + JSON.stringify(name) + '] = function (module, exports, require) {')
  out.push(modules[name])
  out.push('  };')
})
out.push('  module.exports = __require(' + JSON.stringify(entry) + ');')
out.push('})();')
var bundle = out.join('\n') + '\n'

// Duktape-safety guard on the emitted file. Strip comments first so backticks
// and "=>" inside JSDoc/block or line comments don't trip the check — we only
// care about real template literals / arrow functions in code.
var codeOnly = bundle
  .replace(/\/\*[\s\S]*?\*\//g, '') // block comments (incl. JSDoc)
  .replace(/\/\/.*$/gm, '') // line comments
var offenders = codeOnly.split('\n').filter(function (line) {
  return /=>/.test(line) || /`/.test(line)
})
if (offenders.length) {
  console.error('build.js: Duktape-unsafe syntax in bundle:\n' + offenders.join('\n'))
  process.exit(1)
}

fs.mkdirSync(path.dirname(outFile), { recursive: true })
fs.writeFileSync(outFile, bundle)
console.log('build.js: wrote ' + outFile + ' (' + bundle.length + ' bytes, ' + Object.keys(modules).length + ' modules)')
