// OVMS plugin packaging: generate the manifest + assemble the gh-pages repo tree.
// Node-side build tooling (NOT bundled to Duktape). Usage:
//   node publish.js --out <dir>     # assemble plugins.json + abrp/abrp.js into <dir>
//   node publish.js --publish       # build gh-pages and push to origin/gh-pages
var fs = require('fs')
var path = require('path')
var os = require('os')
var childProcess = require('child_process')

function arg(name, def) {
  var i = process.argv.indexOf('--' + name)
  return i !== -1 ? process.argv[i + 1] : def
}

// Builds the plugins.json array (a single abrp plugin entry) for the given version.
function buildManifest(version) {
  return [
    {
      name: 'abrp',
      title: 'A Better Routeplanner (ABRP) Live Telemetry',
      version: version,
      maintainer: 'Jerry Kezar <kezarjg@gmail.com>',
      info: 'https://github.com/kezarjg/ovms-link',
      group: 'Electric Vehicles',
      description: 'Streams live EV telemetry to ABRP via the Iternio Telemetry API.',
      prerequisites: ['ovms>=3.3.004'],
      elements: [
        { type: 'module', path: 'abrp.js', name: 'abrp' },
        { type: 'webrsc', path: 'certdata.js', name: 'abrp_certdata' },
        { type: 'webpage', path: 'config.htm', name: 'abrp_config', label: 'ABRP Config', menu: 'Config', auth: 'admin', page: '/usr/abrp/config' },
        { type: 'webpage', path: 'dashboard.htm', name: 'abrp_status', label: 'ABRP Status', menu: 'Vehicle', auth: 'none', page: '/usr/abrp/status' },
        { type: 'webhook', path: 'status-hook.htm', name: 'abrp_status_hook', page: 'status', hook: 'body.post' },
      ],
    },
  ]
}

// Reads the CA roots from certDir into [{file, pem}] entries (skips non-cert
// files like README.md). These ship as a separate plugin element.
function buildCertData(certDir) {
  return fs
    .readdirSync(certDir)
    .filter(function (f) {
      return /\.(pem|crt)$/.test(f)
    })
    .sort()
    .map(function (f) {
      return { file: f, pem: fs.readFileSync(path.join(certDir, f), 'utf8') }
    })
}

// Renders the cert entries as a Duktape-safe CommonJS module. JSON.stringify
// produces a plain object/array literal (no template literals / arrow functions)
// with newlines escaped inside the PEM strings.
function renderCertData(entries) {
  return (
    '// GENERATED by publish.js from trustedca/ — do not edit.\n' +
    'module.exports = ' +
    JSON.stringify(entries, null, 2) +
    '\n'
  )
}

// Writes the Pages tree into outDir. The on-device OVMS pluginstore expects:
//   plugins.rev  — a single repo revision string; it only refreshes when this
//                  changes, so we emit the plugin version (advances per release).
//   plugins.json — the repo index (an array of plugin summary objects).
//   abrp/abrp.json — the per-plugin manifest OVMS fetches on install: the SINGLE
//                  plugin object (plugins.json[0]), not the array. Missing this,
//                  OVMS saved the 404 HTML and failed with "could not parse metadata".
//   abrp/abrp.js — the bundle (module element).
//   abrp/certdata.js — CA roots from certDir (webrsc element).
//   abrp/*.htm   — the web assets from webDir, one per .htm manifest element.
// Returns the written paths.
function assemblePages(outDir, bundlePath, version, certDir, webDir) {
  certDir = certDir || path.resolve(__dirname, 'trustedca')
  webDir = webDir || path.resolve(__dirname, 'web')
  var manifest = buildManifest(version)
  var pluginDir = path.join(outDir, 'abrp')
  var revPath = path.join(outDir, 'plugins.rev')
  var manifestPath = path.join(outDir, 'plugins.json')
  var pluginJsonOut = path.join(pluginDir, 'abrp.json')
  var moduleOut = path.join(pluginDir, 'abrp.js')
  var certDataOut = path.join(pluginDir, 'certdata.js')
  fs.mkdirSync(pluginDir, { recursive: true })
  fs.writeFileSync(revPath, version + '\n')
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n')
  fs.writeFileSync(pluginJsonOut, JSON.stringify(manifest[0], null, 2) + '\n')
  fs.copyFileSync(bundlePath, moduleOut)
  fs.writeFileSync(certDataOut, renderCertData(buildCertData(certDir)))
  var webOut = []
  manifest[0].elements.forEach(function (el) {
    if (/\.htm$/.test(el.path)) {
      var dest = path.join(pluginDir, el.path)
      fs.copyFileSync(path.join(webDir, el.path), dest)
      webOut.push(dest)
    }
  })
  return {
    revPath: revPath,
    manifestPath: manifestPath,
    pluginJsonOut: pluginJsonOut,
    moduleOut: moduleOut,
    certDataOut: certDataOut,
    webOut: webOut,
  }
}

function run(args, cwd) {
  return childProcess.execFileSync('git', args, { cwd: cwd, stdio: ['ignore', 'pipe', 'pipe'] }).toString()
}

function remoteHasGhPages(repoDir) {
  try {
    run(['ls-remote', '--exit-code', 'origin', 'gh-pages'], repoDir)
    return true
  } catch (e) {
    return false
  }
}

// Publishes the contents of stageDir to origin/gh-pages of repoDir, using a
// temporary git worktree so the main working tree is never disturbed. Creates
// the gh-pages branch (orphan) on first run; replaces its contents on later runs.
function publishToGhPages(repoDir, stageDir, message) {
  var base = fs.mkdtempSync(path.join(os.tmpdir(), 'ghpages-'))
  var wt = path.join(base, 'wt')
  try {
    if (remoteHasGhPages(repoDir)) {
      run(['fetch', 'origin', 'gh-pages'], repoDir)
      run(['worktree', 'add', '-B', 'gh-pages', wt, 'origin/gh-pages'], repoDir)
    } else {
      run(['worktree', 'add', '--detach', wt], repoDir)
      run(['checkout', '--orphan', 'gh-pages'], wt)
    }
    // Start from a clean tree, then lay down the staged files.
    try { run(['rm', '-rf', '.'], wt) } catch (e) { /* empty orphan: nothing to remove */ }
    fs.cpSync(stageDir, wt, { recursive: true })
    run(['add', '-A'], wt)
    run(['commit', '-m', message], wt)
    run(['push', 'origin', 'gh-pages'], wt)
  } finally {
    try { run(['worktree', 'remove', '--force', wt], repoDir) } catch (e) { /* best effort */ }
    try { fs.rmSync(base, { recursive: true, force: true }) } catch (e) { /* best effort */ }
  }
}

module.exports = {
  buildManifest: buildManifest,
  assemblePages: assemblePages,
  publishToGhPages: publishToGhPages,
  buildCertData: buildCertData,
  renderCertData: renderCertData,
}

// --- CLI ---
if (require.main === module) {
  var C = require('./lib/abrp/constants')
  var out = arg('out', null)
  var doPublish = process.argv.indexOf('--publish') !== -1
  var bundle = path.resolve(__dirname, 'dist/abrp.js')
  if ((doPublish || out) && !fs.existsSync(bundle)) {
    console.error('publish.js: ' + bundle + ' not found — run `npm run build` first')
    process.exit(1)
  }
  if (doPublish) {
    var stage = fs.mkdtempSync(path.join(os.tmpdir(), 'abrp-pages-'))
    assemblePages(stage, bundle, C.VERSION)
    publishToGhPages(process.cwd(), stage, 'release: abrp ' + C.VERSION + ' plugin repo')
    console.log('publish.js: published abrp ' + C.VERSION + ' to origin/gh-pages')
  } else if (out) {
    var res = assemblePages(out, bundle, C.VERSION)
    console.log('publish.js: wrote ' + res.revPath + ', ' + res.manifestPath + ', ' + res.pluginJsonOut + ', ' + res.moduleOut + ', and ' + res.certDataOut + ' (version ' + C.VERSION + ')')
  } else {
    console.error('publish.js: expected --out <dir> or --publish')
    process.exit(1)
  }
}
