// OVMS plugin packaging: generate the manifest + assemble the gh-pages repo tree.
// Node-side build tooling (NOT bundled to Duktape). Usage:
//   node publish.js --out <dir>     # assemble plugins.json + abrp/abrp.js into <dir>
//   node publish.js --publish       # build gh-pages and push to origin/gh-pages
var fs = require('fs')
var path = require('path')
var os = require('os')
var childProcess = require('child_process')

function arg(name, def) {
  var i = process.argv.indexOf('--' + name)
  return i !== -1 ? process.argv[i + 1] : def
}

// Version of the abrp-certs plugin (the CA-root installer). Independent of the
// abrp telemetry plugin's version; bump when the trustedca/ set changes.
var CERTS_PLUGIN_VERSION = '1.0.0'

// Builds the plugins.json array. Two plugins ship from this repo:
//   abrp       — the telemetry bundle + web UI
//   abrpcerts  — a small standalone installer for the CA roots abrp's TLS needs
// (kept separate so the abrp module element stays well under the DukTape task
// stack limit — see docs/plugin-repo-hosting.md). Plugin names must be valid JS
// identifiers: OVMS loads each `module` element as `<name> = require(...)`.
function buildManifest(version) {
  return [
    {
      name: 'abrp',
      title: 'A Better Routeplanner (ABRP) Live Telemetry',
      version: version,
      maintainer: 'Jerry Kezar <kezarjg@gmail.com>',
      info: 'https://github.com/kezarjg/ovms-link',
      group: 'Electric Vehicles',
      description: 'Streams live EV telemetry to ABRP via the Iternio Telemetry API.',
      prerequisites: ['ovms>=3.3.004'],
      elements: [
        { type: 'module', path: 'abrp.js', name: 'abrp' },
      ],
    },
    {
      name: 'abrpweb',
      title: 'ABRP Web UI',
      version: version,
      maintainer: 'Jerry Kezar <kezarjg@gmail.com>',
      info: 'https://github.com/kezarjg/ovms-link',
      group: 'Electric Vehicles',
      description: 'Config + status web pages for the ABRP plugin. Requires the abrp plugin.',
      prerequisites: ['ovms>=3.3.004'],
      elements: [
        { type: 'module', path: 'abrpweb.js', name: 'abrpweb' },
        { type: 'webpage', path: 'config.htm', name: 'abrpweb_config', label: 'ABRP Config', menu: 'Config', auth: 'admin', page: '/usr/abrp/config' },
        { type: 'webpage', path: 'dashboard.htm', name: 'abrpweb_status', label: 'ABRP Status', menu: 'Vehicle', auth: 'none', page: '/usr/abrp/status' },
        { type: 'webhook', path: 'status-hook.htm', name: 'abrpweb_status_hook', page: 'status', hook: 'body.post' },
      ],
    },
    {
      name: 'abrpcerts',
      title: 'ABRP CA Certificate Installer',
      version: CERTS_PLUGIN_VERSION,
      maintainer: 'Jerry Kezar <kezarjg@gmail.com>',
      info: 'https://github.com/kezarjg/ovms-link',
      group: 'Electric Vehicles',
      description: 'Installs the CA roots the ABRP plugin needs for its TLS connection to api.iternio.com.',
      prerequisites: ['ovms>=3.3.004'],
      elements: [
        { type: 'module', path: 'abrpcerts.js', name: 'abrpcerts' },
        { type: 'webrsc', path: 'certdata.js', name: 'abrpcerts_certdata' },
      ],
    },
  ]
}

// Reads the CA roots from certDir into [{file, pem}] entries (skips non-cert
// files like README.md). These ship as a separate plugin element.
function buildCertData(certDir) {
  return fs
    .readdirSync(certDir)
    .filter(function (f) {
      return /\.(pem|crt)$/.test(f)
    })
    .sort()
    .map(function (f) {
      return { file: f, pem: fs.readFileSync(path.join(certDir, f), 'utf8') }
    })
}

// Renders the cert entries as a Duktape-safe CommonJS module. JSON.stringify
// produces a plain object/array literal (no template literals / arrow functions)
// with newlines escaped inside the PEM strings.
function renderCertData(entries) {
  return (
    '// GENERATED by publish.js from trustedca/ — do not edit.\n' +
    'module.exports = ' +
    JSON.stringify(entries, null, 2) +
    '\n'
  )
}

// Writes a single manifest element's file into its plugin dir, resolving the
// content by filename: the abrp bundle, the abrpcerts installer, generated CA
// cert data, or a web .htm asset. Returns the written path.
function writeElement(pluginDir, el, src) {
  var dest = path.join(pluginDir, el.path)
  if (el.path === 'abrp.js') {
    fs.copyFileSync(src.bundlePath, dest)
  } else if (el.path === 'abrpcerts.js') {
    fs.copyFileSync(src.certsPluginPath, dest)
  } else if (el.path === 'abrpweb.js') {
    fs.copyFileSync(src.webPluginPath, dest)
  } else if (el.path === 'certdata.js') {
    fs.writeFileSync(dest, renderCertData(buildCertData(src.certDir)))
  } else if (/\.htm$/.test(el.path)) {
    fs.copyFileSync(path.join(src.webDir, el.path), dest)
  } else {
    throw new Error('publish.js: unknown element ' + el.path)
  }
  return dest
}

// Writes the Pages tree into outDir. The on-device OVMS pluginstore expects:
//   plugins.rev  — a single repo revision string; it only refreshes when this
//                  changes, so we emit the abrp version (advances per release).
//   plugins.json — the repo index (an array of plugin summary objects).
//   <name>/<name>.json — the per-plugin manifest OVMS fetches on install: the
//                  SINGLE plugin object (not the array). Missing this, OVMS saved
//                  the 404 HTML and failed with "could not parse metadata".
//   <name>/<element> — one file per element (bundle / installer / certdata / .htm).
// Returns { revPath, manifestPath, plugins: { <name>: { dir, files } } }.
function assemblePages(outDir, bundlePath, version, certDir, webDir, certsPluginPath, webPluginPath) {
  certDir = certDir || path.resolve(__dirname, 'trustedca')
  webDir = webDir || path.resolve(__dirname, 'web')
  certsPluginPath = certsPluginPath || path.resolve(__dirname, 'abrpcerts.js')
  webPluginPath = webPluginPath || path.resolve(__dirname, 'abrpweb.js')
  var manifest = buildManifest(version)
  var revPath = path.join(outDir, 'plugins.rev')
  var manifestPath = path.join(outDir, 'plugins.json')
  fs.mkdirSync(outDir, { recursive: true })
  fs.writeFileSync(revPath, version + '\n')
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n')
  var src = {
    bundlePath: bundlePath,
    certsPluginPath: certsPluginPath,
    webPluginPath: webPluginPath,
    certDir: certDir,
    webDir: webDir,
  }
  var plugins = {}
  manifest.forEach(function (p) {
    var dir = path.join(outDir, p.name)
    fs.mkdirSync(dir, { recursive: true })
    var jsonOut = path.join(dir, p.name + '.json')
    fs.writeFileSync(jsonOut, JSON.stringify(p, null, 2) + '\n')
    var files = [jsonOut]
    p.elements.forEach(function (el) {
      files.push(writeElement(dir, el, src))
    })
    plugins[p.name] = { dir: dir, files: files }
  })
  return { revPath: revPath, manifestPath: manifestPath, plugins: plugins }
}

function run(args, cwd) {
  return childProcess.execFileSync('git', args, { cwd: cwd, stdio: ['ignore', 'pipe', 'pipe'] }).toString()
}

function remoteHasGhPages(repoDir) {
  try {
    run(['ls-remote', '--exit-code', 'origin', 'gh-pages'], repoDir)
    return true
  } catch (e) {
    return false
  }
}

// Publishes the contents of stageDir to origin/gh-pages of repoDir, using a
// temporary git worktree so the main working tree is never disturbed. Creates
// the gh-pages branch (orphan) on first run; replaces its contents on later runs.
function publishToGhPages(repoDir, stageDir, message) {
  var base = fs.mkdtempSync(path.join(os.tmpdir(), 'ghpages-'))
  var wt = path.join(base, 'wt')
  try {
    if (remoteHasGhPages(repoDir)) {
      run(['fetch', 'origin', 'gh-pages'], repoDir)
      run(['worktree', 'add', '-B', 'gh-pages', wt, 'origin/gh-pages'], repoDir)
    } else {
      run(['worktree', 'add', '--detach', wt], repoDir)
      run(['checkout', '--orphan', 'gh-pages'], wt)
    }
    // Start from a clean tree, then lay down the staged files.
    try { run(['rm', '-rf', '.'], wt) } catch (e) { /* empty orphan: nothing to remove */ }
    fs.cpSync(stageDir, wt, { recursive: true })
    run(['add', '-A'], wt)
    run(['commit', '-m', message], wt)
    run(['push', 'origin', 'gh-pages'], wt)
  } finally {
    try { run(['worktree', 'remove', '--force', wt], repoDir) } catch (e) { /* best effort */ }
    try { fs.rmSync(base, { recursive: true, force: true }) } catch (e) { /* best effort */ }
  }
}

module.exports = {
  buildManifest: buildManifest,
  assemblePages: assemblePages,
  writeElement: writeElement,
  publishToGhPages: publishToGhPages,
  buildCertData: buildCertData,
  renderCertData: renderCertData,
}

// --- CLI ---
if (require.main === module) {
  var C = require('./lib/abrp/constants')
  var out = arg('out', null)
  var doPublish = process.argv.indexOf('--publish') !== -1
  var bundle = path.resolve(__dirname, 'dist/abrp.js')
  if ((doPublish || out) && !fs.existsSync(bundle)) {
    console.error('publish.js: ' + bundle + ' not found — run `npm run build` first')
    process.exit(1)
  }
  if (doPublish) {
    var stage = fs.mkdtempSync(path.join(os.tmpdir(), 'abrp-pages-'))
    assemblePages(stage, bundle, C.VERSION)
    publishToGhPages(process.cwd(), stage, 'release: abrp ' + C.VERSION + ' plugin repo')
    console.log('publish.js: published abrp ' + C.VERSION + ' to origin/gh-pages')
  } else if (out) {
    var res = assemblePages(out, bundle, C.VERSION)
    console.log('publish.js: wrote ' + res.manifestPath + ' + plugin trees [' + Object.keys(res.plugins).join(', ') + '] (abrp ' + C.VERSION + ')')
  } else {
    console.error('publish.js: expected --out <dir> or --publish')
    process.exit(1)
  }
}
